language: groovy

# use sudo:true to not use container based infrastructure, for gradle exit value 137 on SIGKILL from Travis issue
sudo: true

jdk:
  - openjdk8

install: true

before_script:
  - cd ..
  - git clone https://github.com/moqui/moqui-framework.git moqui
  - cd moqui
  - chmod +x gradlew

env:
  - TERM=dumb

script:
  - ./gradlew --no-daemon getGit -Pcomponent=mantle-usl
  - ./gradlew --no-daemon load
  - ./gradlew --no-daemon runtime:component:mantle-usl:test --info

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
